Repository jvegaf/LagunaLink-be, pull requests merged in 2021-05, with the labels that each got.

#70 69 enrollments response
  openapi.yaml
  package-lock.json
  package.json
  src/Contexts/LLBE/Enrollments/application/EnrollmentsFetcher.ts
  src/app/lagunalink_be/config/dependency-injection/app/application.yaml
  src/app/lagunalink_be/controllers/enrollments/EnrollmentDeleteController.ts
  src/app/lagunalink_be/controllers/enrollments/EnrollmentPostController.ts
  src/app/lagunalink_be/controllers/enrollments/EnrollmentsFetchController.ts
Labels: size/s

#72 Fecha de contratacion
  api-endpoints.md
  openapi.yaml
  package.json
  src/Contexts/LLBE/JobOpenings/application/Create/CreateJobOpeningRequest.ts
  src/Contexts/LLBE/JobOpenings/application/Create/JobOpeningCreator.ts
  src/Contexts/LLBE/JobOpenings/application/Update/JobOpeningUpgrader.ts
  src/Contexts/LLBE/JobOpenings/application/Update/UpgradeJobOpeningRequest.ts
  src/Contexts/LLBE/JobOpenings/domain/JobOpenHiringDate.ts
  src/Contexts/LLBE/JobOpenings/domain/JobOpening.ts
  src/Contexts/LLBE/Shared/domain/CreatedAt.ts
  src/app/lagunalink_be/controllers/jobOpenings/JobOpeningPostController.ts
  src/app/lagunalink_be/controllers/jobOpenings/JobOpeningPutController.ts
  tests/Contexts/LLBE/Enrollments/domain/EnrollmentDateMother.ts
  tests/Contexts/LLBE/JobOpenings/application/Create/CreateJobOpeningRequestMother.ts
  tests/Contexts/LLBE/JobOpenings/application/Update/UpgradeJobOpeningRequestMother.ts
  tests/Contexts/LLBE/JobOpenings/domain/JobOpenHiringDateMother.ts
  tests/Contexts/LLBE/JobOpenings/domain/JobOpeningMother.ts
  tests/Contexts/LLBE/Shared/domain/EndDateMother.ts
  tests/Contexts/LLBE/Shared/domain/StartDateMother.ts
  tests/Contexts/LLBE/Users/domain/UserCreatedAtMother.ts
  tests/Contexts/LLBE/Users/domain/UserUpdatedAtMother.ts
  tests/Contexts/Shared/domain/FutureDateMother.ts
  tests/Contexts/Shared/domain/PastDateMother.ts
  tests/app/features/jobOpenings/jobOpening.feature
Labels: size/m

#77 Update readme
  README.md
  package-lock.json
Labels: size/xs

#81 Simplify feat
  .eslintrc.js
  .prettierrc.json
  doc/auth.signup.request.http
  openapi.yaml
  package-lock.json
  package.json
  src/Contexts/LLBE/Companies/application/Create/CompanyCreator.ts
  src/Contexts/LLBE/Companies/domain/CompanyName.ts
  src/Contexts/LLBE/Companies/domain/CompanyPostalCode.ts
  src/Contexts/LLBE/Shared/application/Users/RoleAccountCreator.ts
  src/Contexts/LLBE/Shared/domain/StartDate.ts
  src/Contexts/LLBE/Students/application/Create/StudentCreator.ts
  src/Contexts/LLBE/Users/application/AuthResponse.ts
  src/Contexts/LLBE/Users/application/CreateUserRequest.ts
  src/Contexts/LLBE/Users/application/UserAuth.ts
  src/Contexts/LLBE/Users/application/UserCreator.ts
  src/Contexts/LLBE/Users/application/UserEmailConfirmator.ts
  src/Contexts/LLBE/Users/application/UserUpdateRegistered.ts
  src/Contexts/LLBE/Users/domain/User.ts
  src/Contexts/LLBE/Users/domain/UserRegistered.ts
  src/Contexts/LLBE/Users/infrastructure/persistence/mongo/UserDocument.ts
  src/Contexts/Shared/domain/value-object/IntValueObject.ts
  src/app/lagunalink_be/config/dependency-injection/Companies/application.yaml
  src/app/lagunalink_be/config/dependency-injection/Students/application.yaml
  src/app/lagunalink_be/config/dependency-injection/Users/application.yaml
  src/app/lagunalink_be/config/dependency-injection/app/application.yaml
  src/app/lagunalink_be/controllers/auth/SignInPostController.ts
  src/app/lagunalink_be/controllers/auth/SignUpPostController.ts
  src/app/lagunalink_be/controllers/companies/CompanyPostController.ts
  src/app/lagunalink_be/controllers/students/StudentPostController.ts
  src/app/lagunalink_be/controllers/user/ProfileGetController.ts
  src/app/lagunalink_be/routes/avatar.route.ts
  src/app/lagunalink_be/routes/companies.route.ts
  src/app/lagunalink_be/routes/enrollments.route.ts
  src/app/lagunalink_be/routes/students.route.ts
  src/app/lagunalink_be/routes/user.route.ts
  tests/Contexts/LLBE/Companies/application/Create/CompanyCreator.test.ts
  tests/Contexts/LLBE/Companies/application/Create/CreateCompanyRequestMother.ts
  tests/Contexts/LLBE/Shared/__mocks__/UserUpdateRegisteredMock.ts
  tests/Contexts/LLBE/Students/application/Create/CreateStudentRequestMother.ts
  tests/Contexts/LLBE/Students/application/Create/StudentCreator.test.ts
  tests/Contexts/LLBE/Users/application/CreateUserRequestMother.ts
  tests/Contexts/LLBE/Users/domain/UserMother.ts
  tests/Contexts/LLBE/Users/domain/UserRegisteredMother.ts
  tests/app/features/auth/userSignUp.feature
  tests/app/features/avatar/avatar.feature
  tests/app/features/companies/company.feature
  tests/app/features/enrollments/enrollment.feature
  tests/app/features/step_definitions/controller.steps.ts
  tests/app/features/students/student.feature
  tsconfig.json
Labels: size/l
